### ISSUE TITLE
Some minor issues with opcodes.

### ISSUE THREAD

**Issue by frozenLake** [CTurt/GameBoy_GhidraSleigh#1]
Hey, I was going over a disassembly of Pokemon TCG, and noticed that a few of the opcodes were... somewhat off. I'll go ahead and list the ones I managed to find.

0xD9: Missing "RETI" instruction
0xE8: Uses one more byte than it should.
0xF8: Uses one more byte than it should.

**Comment by CTurt** [comment]
Hi, thanks for your report.

You’re absolutely right. Turns out I was using ; as “or” when it actually means run the condition on the next byte, for some opcodes early on and never went back to check.

I’ll fix it when I get home from work.

**Comment by CTurt** [comment]
Hi,

Thanks for your report!

I believe I have fixed the issue with this commit:

https://github.com/CTurt/GameBoy_GhidraSleigh/commit/980e2073e2c35d23ef1820fcc24818c47682f905
